### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by yonaskolb** [vadymmarkov/Fashion#5]
Any plans to update to Swift 3?

**Comment by zenangst** [comment]
Hey @yonaskolb, version 2.0.0 is already in Swift 3 :)

**Comment by dinarajas** [comment]
@zenangst Do you have any specific version for swift 2.3?

**Comment by vadymmarkov** [comment]
@dineshrajas Unfortunately we don't have swift 2.3 version. The library was migrated straight to 3.0.
